
title: CSCI-UA 480 (Open Source Software Development, Sp 2025)
description: "Course website for CSCI-UA 480 (Open Source Software Development) course."

baseurl: "/ossd_s25" 
url: "https://joannakl.github.io/ossd" # the base hostname & protocol for your site, e.g. http://example.com

markdown: kramdown
kramdown:
  entity_output: numeric
  smart_quotes: apos,apos,quot,quot

exclude:
  - Gemfile
  - Gemfile.lock



course_number: "CSCI-UA 480"
course_name: "Open Source Software Development"
course_section: "061"
course_semester: "Spring 2025"
course_time: "Mondays, Wednesdays 12:30pm - 1:45pm"
course_location: "60 Fifth Ave 110"



instructor_office_hours: "TBD<br/>
(or you can schedule an appointment if these times do not work for you, I can usually meet right before our class)"
instructor_office_hours_location: "Zoom, links available on Brightspace"

tutor_office_hours: ""
tutor_name: ""


tutor_location: ""
tutor_schedule_link: ""


current_course1_title: "CSCI 102 sec. 1"
current_course1_link: "https://cs.nyu.edu/~joannakl/cs102/"
current_course3_title: "CSCI 480 sec. 61 (OSSD)"
current_course3_link: "https://cs.nyu.edu/~joannakl/ossd_s25/"
current_course3_title: ""
current_course3_link: ""

midterm_exam_date: "TBD (do not plan on leaving for the spring break ahead of time)"
final_exam_date: "TBD"
final_exams_link: "http://cs.nyu.edu/dynamic/courses/exams/"

piazza_site: https://edstem.org
gradescope_site: ""
github_site: https://github.com/ossd-s25/
website_github_site: https://github.com/joannakl/ossd

book_opt_1: "Producing Open Source Software, "
book_opt_1_author: "Karl Fogel, "
book_opt_1_edition: "2nd edition, "
book_opt_1_link: "http://producingoss.com/"
book_opt_1_note: ""
book_opt_1_image: "http://producingoss.com/images/producingoss-cover-small.gif"


book_opt_2: "The Architecture of Open Source Applications, "
book_opt_2_author: "Amy Brown and Greg Wilson (editors), "
book_opt_2_edition: ""
book_opt_2_link: "http://www.aosabook.org/en/index.html"
book_opt_2_note: ""
book_opt_2_image: "https://aosabook.org/static/cover1.jpg"


book_opt_3: "Practical Open Source Software Exploration, "
book_opt_3_author: "Greg DeKoenigsberg, Chris Tyler, Karsten Wade, Max Spevack, Mel Chua, and Jeff Sheltren, "
book_opt_3_edition: ""
book_opt_3_link: "https://quaid.fedorapeople.org/TOS/Practical_Open_Source_Software_Exploration/html/"
book_opt_3_note: "(it hasn't been updated since 2010, but there is some good stuff in there)"
book_opt_3_image: ""


book_opt_4: "The Linux Command Line, "
book_opt_4_author: "William Shotts, "
book_opt_4_edition: ""
book_opt_4_link: "http://linuxcommand.org/tlcl.php"
book_opt_4_note: ""
book_opt_4_image: "http://linuxcommand.org/images/lcl2_front_new.png"


book_opt_5: "ProGit, "
book_opt_5_author: "Scott Chacon and Ben Straub, "
book_opt_5_edition: "2nd edition"
book_opt_5_link: "https://git-scm.com/book/en/v2"
book_opt_5_note: ""
book_opt_5_image: "https://git-scm.com/images/progit2.png"


book_opt_6: "The Cathedral and the Bazaar, "
book_opt_6_author: "Eric Steven Raymond, "
book_opt_6_edition: ""
book_opt_6_link: "http://www.catb.org/~esr/writings/cathedral-bazaar/"
book_opt_6_note: "printed version available from [O'Reilly](http://shop.oreilly.com/product/9781565927247.do)"
book_opt_6_image: "https://upload.wikimedia.org/wikipedia/en/c/c4/Cathedral-and-the-Bazaar-book-cover.jpg"


book_opt_7: "Forge Your Future with Open Source, "
book_opt_7_author: "VM (Vicky) Brasseur, "
book_opt_7_edition: ""
book_opt_7_link: "https://archive.org/details/isbn_9781680503012/mode/2up"
book_opt_7_note: "available through Open Library (link above), or through [O'Reilly](https://learning.oreilly.com/library/view/forge-your-future/9781680506389/f_0000.xhtml) with your NYU credentials"
book_opt_7_image: "https://imagery.pragprog.com/products/542/vbopens_xlargecover.jpg?1516635915"


book_opt_8: "Open Source: What It Is and How to Contribute, "
book_opt_8_author: "Jan Pearce, "
book_opt_8_edition: ""
book_opt_8_link: "https://runestone.academy/ns/books/published/opensource/meta_frontmatter.html"
book_opt_8_note: "digital, web-based version of the book"
book_opt_8_image: ""
